services:
  my_candidate_pg:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  my_candidate_redis:
    image: redis:7
    ports:
      - "6379:6379"

  my_candidate_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - my_candidate_pg
      - my_candidate_redis
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      REDIS_URL: ${REDIS_URL}

  my_candidate_sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - my_candidate_pg
      - my_candidate_redis
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      REDIS_URL: ${REDIS_URL}

volumes:
  pg_data:
