apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_HOST: db-postgresql-nyc1-66275-do-user-13738821-0.h.db.ondigitalocean.com
  DB_NAME: defaultdb
  DB_USER: doadmin
  DB_PASSWORD: AVNS_1aq-tdnyssskjUbH-Le
