apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycandidate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycandidate
  template:
    metadata:
      labels:
        app: mycandidate
    spec:
      containers:
        - name: mycandidate
          image: joaoneto123/my_candidate:latest
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key_base
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
