apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  secret_key_base: MzcwMjU0OTA1YWE3MWFiOTE1ODBlMmNhYzBjMzFmZmU4M2ZkZTJlOGM5NmNlZjBjM2YyNGYxM2E0M2MzNTcwMjI5NzYyYmNlZWE2Y2RkYTkwY2E1YmU4ZTIyZmRjMWU3OTE5ZTViN2M4N2RkNGNmZGJhODhmNDJjMTAzODZjYTQ=