name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: RSpec & RuboCop
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

      redis:
        image: redis:7
        ports: ['6379:6379']

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/app_test
      REDIS_URL: redis://localhost:6379/1

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Ruby e Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: Instalar dependências do sistema
        run: sudo apt-get update && sudo apt-get install -y libpq-dev libvips

      - name: Criar banco de dados
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Rodar RuboCop
        run: bundle exec rubocop

      - name: Rodar RSpec
        run: bundle exec rspec
